#!/bin/sh
cd /project/ansible

# Fixes bug: https://github.com/symfony/symfony/issues/12533
rm -fR ../app/cache > /dev/null 2>&1 &
rm -fR ../app/logs > /dev/null 2>&1 &

ansible-playbook update.yml -i inventories/build --tags "services,shared_directories,always"
