#!/bin/sh
cd /project/ansible

# Fixes bug: https://github.com/symfony/symfony/issues/12533
rm -fR ../app/cache

ansible-playbook update.yml -i inventories/build --tags "services,shared_directories,always"
