#!/bin/bash
set -e

MYSQL_RAM_SIZE=${MYSQL_RAM_SIZE:-"2048"}
MYSQL_DB=${MYSQL_DB:-"/var/lib/mysql"}

echo "Mounting MySQL with ${MYSQL_RAM_SIZE}MB of RAM."

# Move away old mysql data
mkdir -p /opt/mysql_backup
test -d ${MYSQL_DB} && mv ${MYSQL_DB} /opt/mysql_backup

id -u mysql &>/dev/null || useradd mysql
mkdir ${MYSQL_DB} && chown mysql ${MYSQL_DB}

sudo mount -v -t tmpfs -o size="${MYSQL_RAM_SIZE}m" tmpfs ${MYSQL_DB}
