#!/bin/sh

if [ -z "$1" ]; then
    exit 0;
fi

#ping -c 1 SERVER_NAME_HERE &> /dev/null
nc $1 3142 < /dev/null

if [ $? = "0" ]; then
  echo "Acquire::http::Proxy \"http://$1:3142\";" > /etc/apt/apt.conf.d/01proxy
else
  rm /etc/apt/apt.conf.d/01proxy &> /dev/null
fi

exit 0;
